import type { Express } from "express";
import { type Server } from "http";
import { setupWebSocketServer } from "./agent";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, ExternalHyperlink, BorderStyle, AlignmentType } from "docx";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  setupWebSocketServer(httpServer);

  app.post("/api/export/word", async (req, res) => {
    try {
      const { results, query } = req.body;

      if (!results || !Array.isArray(results) || results.length === 0) {
        return res.status(400).json({ message: "No results to export" });
      }

      const children: Paragraph[] = [];

      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "CITADELLE LEGAL BRIEF",
              bold: true,
              size: 36,
              font: "Calibri",
              color: "1e3a5f",
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `Research Query: "${query || "N/A"}"`,
              italics: true,
              size: 22,
              font: "Calibri",
              color: "666666",
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
              size: 20,
              font: "Calibri",
              color: "999999",
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 300 },
        }),
        new Paragraph({
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 6, color: "1e3a5f" },
          },
          spacing: { after: 300 },
        })
      );

      results.forEach((item: any, index: number) => {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `${index + 1}. ${item.caseTitle || "Untitled Case"}`,
                bold: true,
                size: 26,
                font: "Calibri",
                color: "1e3a5f",
              }),
            ],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 240, after: 120 },
          })
        );

        if (item.court || item.date) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: [item.court, item.date].filter(Boolean).join("  •  "),
                  size: 20,
                  font: "Calibri",
                  color: "666666",
                }),
              ],
              spacing: { after: 80 },
            })
          );
        }

        if (item.snippet) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: item.snippet,
                  size: 22,
                  font: "Calibri",
                }),
              ],
              spacing: { after: 80 },
            })
          );
        }

        if (item.url && item.url.startsWith("http")) {
          children.push(
            new Paragraph({
              children: [
                new ExternalHyperlink({
                  children: [
                    new TextRun({
                      text: item.url,
                      style: "Hyperlink",
                      size: 18,
                      font: "Calibri",
                    }),
                  ],
                  link: item.url,
                }),
              ],
              spacing: { after: 200 },
            })
          );
        }

        children.push(
          new Paragraph({
            border: {
              bottom: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
            },
            spacing: { after: 200 },
          })
        );
      });

      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "Generated by Citadelle Web-Agent — AI-Powered Legal Research",
              italics: true,
              size: 18,
              font: "Calibri",
              color: "999999",
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
        })
      );

      const doc = new Document({
        sections: [{ children }],
      });

      const buffer = await Packer.toBuffer(doc);

      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", "attachment; filename=Citadelle_Legal_Brief.docx");
      res.send(buffer);
    } catch (err: any) {
      console.error("DOCX export error:", err);
      res.status(500).json({ message: "Failed to generate document" });
    }
  });

  return httpServer;
}
